export const FILTER_CHANGE = "FILTER_CHANGE";
export const GAME_LIST_CHANGE = "GAME_LIST_CHANGE";
export const FILTER_CHANGE_TO_DEFAULT = "FILTER_CHANGE_TO_DEFAULT";
export const BASKET_LIST_CHANGE = "BASKET_LIST_CHANGE";
export const BASKET_LIST_TO_DEFAULT = "BASKET_LIST_TO_DEFAULT";